[package]
name = "HardwareSimulator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sdl2 = "0.32.0"

[dev-dependencies]
rstest = "0.19.0"